services:
  mariadb:
    image: mariadb:10.6
    container_name: moodle-mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=moodle_root_pass
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle_user
      - MYSQL_PASSWORD=moodle_pass
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - moodle_network

  moodle:
    image: moodle:4.1-apache
    container_name: moodle-app
    ports:
      - "8080:80"
    restart: always
    environment:
      - MOODLE_DB_HOST=mariadb
      - MOODLE_DB_NAME=moodle
      - MOODLE_DB_USER=moodle_user
      - MOODLE_DB_PASSWORD=moodle_pass
      - MOODLE_DB_TYPE=mariadb
    volumes:
      - moodle_data:/var/www/html
      - moodle_app_data:/var/moodledata
    depends_on:
      - mariadb
    networks:
      - moodle_network

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodle_app_data:
    driver: local

networks:
  moodle_network:
    driver: bridge
