version: '3.8'

services:
  mariadb:
    image: bitnami/mariadb:11.4.2-debian-12-r0
    container_name: moodle-mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=moodle_root_pass
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_USER=moodle_user
      - MARIADB_PASSWORD=moodle_pass
    volumes:
      - mariadb_data:/bitnami/mariadb

  moodle:
    image: bitnami/moodle:4-debian-12
    container_name: moodle-app
    ports:
      - 8080:8080
      - 8443:8443
    restart: always
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_USER=moodle_user
      - MOODLE_DATABASE_PASSWORD=moodle_pass
    volumes:
      - moodle_data:/bitnami/moodle
      - moodle_app:/bitnami/moodledata
    depends_on:
      - mariadb

volumes:
  mariadb_data:
  moodle_data:
  moodle_app:
